remote_theme: yaoyao-liu/minimal-light

# Basic Information 
title: Jiaheng Zhuang
position: Ph.D. Student
affiliation: Tsinghua University
email: jiaheng.biz@gmail.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: 庄嘉恒
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light-theme.yliu.me/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/
cv_link: files/Curriculum_Vitae.pdf
github_link: https://github.com/zhuangjiaheng/
# linkedin: https://www.linkedin.com/
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
# Replace with your images in your repo
avatar: avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
